
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: assignment_sql_server
    cap_add:
      - SYS_PTRACE
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Assignment123$" 
      MSSQL_PID: "Developer"
      MSSQL_USER: "sa"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: